data:
  data_path: /Users/maevemadigan/Documents/*Work/Misc/model-analysis/src/data-files/CMS_mtt_1D_RunII/HEPData-ins1901295-v1-parton_abs_ttm.csv
  covmat_path: /Users/maevemadigan/Documents/*Work/Misc/model-analysis/src/data-files/CMS_mtt_1D_RunII/HEPData-ins1901295-v1-parton_abs_ttm_covariance.csv
  data_label: CMS_mtt_1D_RunII


model:
  model_path: /Users/maevemadigan/Documents/*Work/Misc/model-analysis/src/model-files/CMS_mtt_1D_RunII_ALPS
  SM_file: mtt_nnpdf4p0_alphaS_SM.txt
  model_file_lin: mtt_nnpdf4p0_alphaS_lin.txt
  model_file_quad: mtt_nnpdf4p0_alphaS_quad.txt
  model_format: None
  model_label: ALPS #will feature in the model_constructor choice
    #kfactor: kfac_nnlo_lo.txt
  kfactor: kfac_nnlo_lo_highstats.txt
  BR: 0.2877

plotting:
  params_to_plot: [0.0, 4.0, 12.0, 20.0]

defaults: 
  - default
  - _self_



