data:
  data_path: /Users/maevemadigan/Documents/*Work/Misc/model-analysis/src/data-files/CMS_mtt_1D_2018/HEPData-ins1901295-v1-parton_abs_ttm.csv
  covmat_path: /Users/maevemadigan/Documents/*Work/Misc/model-analysis/src/data-files/CMS_mtt_1D_2018/HEPData-ins1901295-v1-parton_abs_ttm_covariance.csv
  data_label: CMS_mtt_1D_RunII


model:
  model_path: /Users/maevemadigan/Documents/*Work/Misc/model-analysis/src/model-files/CMS_mtt_1D_2018_ALPS
  SM_file: mtt_nnpdf4p0_alphaS_SM.txt
  model_file_lin: mtt_nnpdf4p0_alphaS_lin.txt
  model_file_quad: mtt_nnpdf4p0_alphaS_quad.txt
  model_format: None
  model_label: ALPS #will feature in the model_constructor choice
  kfactor: None


run_name: null
out_dir: ./outputs
seed: null


plot: True
limits: True
statistic: chi2

#Plot settings
font: {"size": 13}
plottitle:  "CMS data compared to SM+ALP signal"
plotxlabel: "$m_{t \\bar{t}}$ [GeV]"
plotylabel: "$\\frac{d \\sigma}{d m_{t \\bar{t}}}$ [pb/GeV]"
plotfilename: "CMS_mtt_ALP.pdf"
